all:

review_polarity: ../download/review_polarity.tar.gz
	mkdir -p review_polarity
	cd review_polarity; tar xvzf ../$<

geoquery: ../download/geoquery.tar.gz
	tar xvzf $<

maptask: ../download/maptask.tgz
	tar xvzf $<

wsj: ../download/treebank3-parsed-mrg-wsj.tgz
	tar xvzf $<
